<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.Yusuf</groupId>
    <artifactId>SocialMedia</artifactId>
    <version>0.0.1-SNAPSHOT</version>
  </parent>
  <artifactId>ConfigServer</artifactId>
  
  <!--Mikroservis mimarisinde onlarca proje olur. Her birinin configuration ayarını tek tek içine yazmak yerine,
   tüm ayarları GitHub(veya başka repo)'da tek bir depoda tutarız. Config Server bu depoya bağlanır. 
   Diğer servisler (Auth, User) ayağa kalkarken Config Server'dan kendi ayarlarını çeker. 
   Şifre değiştiğinde sadece GitHub'ı güncelleriz, kodlara dokunmayız!-->
  <dependencies>
  
  <!--Uygulamanın ilk ayağa kalkış rehberidir. Kendi ayarlarından önce Config Server'ın adresini öğrenmek için 'bootstrap.properties' dosyasını okumasını sağlar.-->
    <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-starter-bootstrap</artifactId>
    </dependency>
    
  <!--Bu projeyi GitHub'daki ayarları okuyup diğerlerine dağıtan Merkezi Sunucu (Beyin) haline getirir.-->
    <dependency>
         <groupId>org.springframework.cloud</groupId>
         <artifactId>spring-cloud-config-server</artifactId>
    </dependency>
    
    <!--Projeyi bir İstemci (Client) yapar. Servislerin kendi ayarlarını merkezi Config Server'dan çekebilmesini sağlar.-->
    <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-starter-config</artifactId>
    </dependency>
    
     <!--GitHub'da bir ayar güncellediğimizde, projeyi tamamen kapatıp açmaya gerek kalmadan ayarların anında sisteme yansımasını sağlar (/refresh komutu ile)-->
    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-actuator</artifactId>
    </dependency>
    
    <!--SpringBoot u entegre eder, Config Server'ın 8888 portu gibi bir HTTP portu üzerinden çalışmasını ve gelen ayar isteklerine JSON formatında cevap vermesini sağlar.-->
    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    
   

</dependencies>
  
  
  
  
</project>
