# 1. Config Server'ın adresi
#spring.cloud.config.uri=http://localhost:8888

# 2. Uygulamanın Adı (GitHub'daki ayar dosyanın adıyla BİREBİR aynı olmalı)
spring.application.name=user-application

# 3. YENİ NESİL BAĞLANTI: Ayarları Config Server'dan içe aktar
spring.config.import=configserver:http://localhost:8888