spring.application.name=MealService
server.port=8082
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=21
spring.jpa.properties.hibernate.default_schema=gelisim
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.cloud.config.enabled=false