spring.application.name=AiVisualizationService
server.port=8083
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=21
spring.jpa.properties.hibernate.default_schema=gelisim
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Dosyaların kaydedileceği ana klasör yolu (Eğik çizgilere DİKKAT)
file.upload-dir=D:/VucutGelisimProje/AiTransformationImages

# API Key
replicate.api.key=####ReplicateApıKey####

jwt.secret=YmVuaW1Db2tHaXpsaVZlR3V2ZW5saVNpZnJlbTEyMzQ1Njc4OTA=
internal.secret=SistemIciCokGizliSifreVucutGelisim2026
