spring.application.name=AuthService

# 1. AuthService'in çalışacağı port (8080, 8081, 8082 dolu olduğu için 8085 idealdir)
server.port=8084

# 2. İleride JWT (Token) üretirken kullanacağımız gizli anahtarı ve süreyi de 
# merkezi olarak burada saklayacağız. Şimdilik taslak olarak ekleyelim:
jwt.secret=YmVuaW1Db2tHaXpsaVZlR3V2ZW5saVNpZnJlbTEyMzQ1Njc4OTA=
jwt.expires-in=86400000
