# Sunucu Portu
server.port=8888

# Uygulama Adı
spring.application.name=ConfigServer

# Git Reposu Yapılandırması
spring.cloud.config.server.git.uri=https://github.com/Azad-star/Body-Development-ConfigServer.git
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.skip-ssl-validation=true

# GitHub Kimlik Bilgileri
spring.cloud.config.server.git.username=Azad-star
# Buraya GitHub Personal Access Token 
spring.cloud.config.server.git.password= #GitHubPersonelAccessToken

# Proje başlarken GitHub'a bağlanmaya zorlar (bağlantı hatalarını erkenden yakalar).
spring.cloud.config.server.git.clone-on-start=true

# Eski veya bozuk yerel dosyaları yok sayıp, her zaman GitHub'daki en güncel versiyonu zorla indirir.
spring.cloud.config.server.git.force-pull=true

# Git dosyalarını gizli ve karmaşık Temp klasörü yerine, doğrudan projenin 'target' klasörüne temiz bir şekilde indirir.
spring.cloud.config.server.git.basedir=target/config-repo-yeni
